# Generated by Django 5.1.7 on 2025-03-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
