# Generated by Django 5.1.7 on 2025-03-25 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_service", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="media_service.post",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_posts",
                to="media_service.profile",
            ),
        ),
    ]
